# Generated by Django 4.2.8 on 2026-01-15 09:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('success', 'Succès'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Congés payés'), ('sick', 'Congé maladie'), ('unpaid', 'Congé sans solde'), ('maternity', 'Congé maternité'), ('paternity', 'Congé paternité'), ('personal', 'Raison personnelle'), ('training', 'Formation'), ('other', 'Autre')], max_length=20, verbose_name='Type de congé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('days_requested', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Nombre de jours')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de refus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='employees.employee', verbose_name='Approuvé par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contrat de travail'), ('payslip', 'Fiche de paie'), ('certificate', 'Attestation'), ('medical', 'Document médical'), ('id', "Pièce d'identité"), ('diploma', 'Diplôme'), ('other', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidentiel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='Employé')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='employees.employee', verbose_name='Téléchargé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Année')),
                ('vacation_days_total', models.DecimalField(decimal_places=1, default=Decimal('25.0'), max_digits=5, verbose_name='Total congés payés')),
                ('vacation_days_taken', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Congés payés pris')),
                ('sick_days_taken', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Jours maladie pris')),
                ('other_days_taken', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Autres jours pris')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_balance', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Solde de congés',
                'verbose_name_plural': 'Soldes de congés',
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
