# Generated by Django 4.2.8 on 2026-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='portal_leav_status_37be35_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee'], name='portal_leav_employe_c99b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date'], name='portal_leav_start_d_840b09_idx'),
        ),
    ]
