# Generated by Django 4.2.8 on 2026-01-14 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ambulancier_dea', 'Ambulancier DEA'), ('auxiliaire_ambulancier', 'Auxiliaire ambulancier'), ('chauffeur_vsl', 'Chauffeur VSL'), ('chauffeur_taxi', 'Chauffeur taxi'), ('assistant_rh', 'Assistant RH'), ('responsable_rh', 'Responsable RH'), ('responsable_exploitation', "Responsable d'exploitation"), ('comptable', 'Comptable'), ('apprenti', 'Apprenti'), ('stagiaire', 'Stagiaire')], help_text='Code unique de la profession', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Libellé de la profession', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description des responsabilités')),
                ('is_active', models.BooleanField(default=True, help_text="Profession active dans l'entreprise")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Numéro/ID interne du salarié', max_length=20, unique=True)),
                ('birth_date', models.DateField(help_text='Date de naissance')),
                ('birth_place', models.CharField(blank=True, help_text='Lieu de naissance', max_length=100)),
                ('nationality', models.CharField(blank=True, default='Français(e)', help_text='Nationalité', max_length=100)),
                ('address', models.CharField(help_text='Adresse du domicile', max_length=200)),
                ('postal_code', models.CharField(help_text='Code postal', max_length=5, validators=[django.core.validators.RegexValidator(message='Le code postal doit contenir 5 chiffres', regex='^\\d{5}$')])),
                ('city', models.CharField(help_text='Ville', max_length=100)),
                ('country', models.CharField(default='France', help_text='Pays', max_length=100)),
                ('phone', models.CharField(help_text='Numéro de téléphone personnel', max_length=17, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être valide', regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact', models.CharField(blank=True, help_text='Personne à contacter en urgence', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, help_text="Téléphone du contact d'urgence", max_length=17, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être valide', regex='^\\+?1?\\d{9,15}$')])),
                ('social_security_number', models.CharField(help_text='Numéro de sécurité sociale', max_length=15, unique=True)),
                ('rib', models.CharField(blank=True, help_text="RIB (Relevé d'Identité Bancaire)", max_length=27)),
                ('qualification', models.CharField(blank=True, help_text='Qualifications spécifiques (DEA, etc.)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('left', 'Sorti')], default='active', help_text='Statut du salarié', max_length=20)),
                ('date_entry', models.DateField(help_text="Date d'entrée dans l'entreprise")),
                ('date_exit', models.DateField(blank=True, help_text="Date de sortie de l'entreprise", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Utilisateur qui a créé le salarié', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('profession', models.ForeignKey(help_text='Profession/Métier du salarié', on_delete=django.db.models.deletion.PROTECT, to='employees.profession')),
                ('user', models.OneToOneField(help_text='Utilisateur lié au salarié', on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salarié',
                'verbose_name_plural': 'Salariés',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'), models.Index(fields=['status'], name='employees_e_status_61c2f6_idx'), models.Index(fields=['date_entry'], name='employees_e_date_en_e02acb_idx')],
            },
        ),
    ]
