# Generated by Django 4.2.8 on 2026-01-16 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contrat de travail'), ('amendment', 'Avenant'), ('id_card', "Pièce d'identité"), ('diploma', 'Diplôme'), ('certificate', 'Certificat médical'), ('payslip', 'Bulletin de salaire'), ('attestation', 'Attestation'), ('insurance', 'Assurance'), ('other', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('is_visible_to_employee', models.BooleanField(default=True, verbose_name='Visible par le salarié')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ged_documents', to='employees.employee', verbose_name='Employé')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document salarié',
                'verbose_name_plural': 'Documents salariés',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
