# Generated by Django 4.2.8 on 2026-01-16 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('embauche', "Visite d'embauche"), ('periodique', 'Visite périodique'), ('reprise', 'Visite de reprise'), ('mi_carriere', 'Visite mi-carrière'), ('aptitude', "Visite d'aptitude"), ('autre', 'Autre')], max_length=50, verbose_name='Type de visite')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Date effectuée')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('completed', 'Effectuée'), ('cancelled', 'Annulée'), ('to_schedule', 'À planifier')], default='to_schedule', max_length=20, verbose_name='Statut')),
                ('doctor_name', models.CharField(blank=True, max_length=200, verbose_name='Médecin du travail')),
                ('result', models.CharField(blank=True, choices=[('apte', 'Apte'), ('apte_reserve', 'Apte avec réserves'), ('inapte', 'Inapte'), ('', 'Non renseigné')], max_length=50, verbose_name='Résultat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='Prochaine visite prévue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Visite médicale',
                'verbose_name_plural': 'Visites médicales',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
