# Generated by Django 4.2.8 on 2026-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeedocument_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', help_text='Genre (pour les accords dans les contrats)', max_length=1),
        ),
    ]
