# Generated by Django 4.2.8 on 2026-01-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Numéro unique du contrat', max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI - Contrat à Durée Indéterminée'), ('cdd', 'CDD - Contrat à Durée Déterminée'), ('apprenticeship', "Contrat d'apprentissage"), ('professionalization', 'Contrat de professionnalisation'), ('internship', 'Stage')], help_text='Type de contrat', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('terminated', 'Terminé'), ('expired', 'Expiré')], default='active', help_text='Statut du contrat', max_length=20)),
                ('contract_status', models.CharField(choices=[('trial', "Période d'essai"), ('confirmed', 'Confirmé')], default='trial', help_text='Phase du contrat (essai ou confirmé)', max_length=20)),
                ('start_date', models.DateField(help_text='Date de début du contrat')),
                ('end_date', models.DateField(blank=True, help_text='Date de fin du contrat (pour CDD, stage, etc.)', null=True)),
                ('trial_end_date', models.DateField(blank=True, help_text="Date de fin de la période d'essai", null=True)),
                ('working_hours_per_week', models.DecimalField(decimal_places=2, default=35.0, help_text="Nombre d'heures de travail par semaine", max_digits=5)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Taux horaire', max_digits=10, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire mensuel', max_digits=10, null=True)),
                ('collective_agreement', models.CharField(default='Convention collective du transport sanitaire', help_text='Convention collective applicable', max_length=200)),
                ('collective_agreement_date', models.DateField(blank=True, help_text='Date de la convention collective', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes spécifiques sur le contrat')),
                ('contract_file', models.FileField(blank=True, help_text='Fichier du contrat (PDF)', null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Utilisateur qui a créé le contrat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Salarié associé au contrat', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', 'status'], name='contracts_c_employe_966f59_idx'), models.Index(fields=['start_date'], name='contracts_c_start_d_4c01aa_idx'), models.Index(fields=['end_date'], name='contracts_c_end_dat_dedd36_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date')), ('end_date__isnull', True), _connector='OR'), name='check_contract_dates'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('working_hours_per_week__gt', 0)), name='check_positive_hours'),
        ),
    ]
