# Generated by Django 4.2.8 on 2026-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_add_occupational_health_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='entity_template',
            field=models.CharField(blank=True, choices=[('nantes_urgences', 'Nantes Urgences Sansoucy'), ('ambulances_sansoucy', 'Ambulances Sansoucy')], help_text='Entité pour laquelle générer le contrat', max_length=30, null=True),
        ),
    ]
