# Generated by Django 4.2.8 on 2026-01-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('day', 'Jour'), ('night', 'Nuit'), ('sunday', 'Dimanche'), ('holiday', 'Férié'), ('early', 'Tôt'), ('late', 'Tard')], help_text='Type de shift', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du type de shift')),
                ('start_hour', models.TimeField(help_text='Heure de début standard')),
                ('end_hour', models.TimeField(help_text='Heure de fin standard')),
                ('base_hours', models.DecimalField(decimal_places=2, default=8, help_text="Nombre d'heures de base pour ce type de shift", max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Ce type de shift est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de shift',
                'verbose_name_plural': 'Types de shifts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date du shift')),
                ('start_time', models.TimeField(help_text='Heure de début réelle')),
                ('end_time', models.TimeField(help_text='Heure de fin réelle')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('ongoing', 'En cours'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='planned', help_text='Statut du shift', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur le shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Créé par', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('shift_type', models.ForeignKey(help_text='Type de shift', on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='planning.shifttype')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigné'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('absent', 'Absent'), ('cancelled', 'Annulé')], default='assigned', help_text="Statut de l'assignment", max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Notes sur l'assignment")),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Date de confirmation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employé assigné', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.employee')),
                ('shift', models.ForeignKey(help_text='Shift assigné', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='planning.shift')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Véhicule assigné (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-shift__date', 'employee__user__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('date', 'start_time', 'shift_type'), name='unique_shift_per_date_time_type'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('shift', 'employee'), name='unique_assignment_per_shift_employee'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle__isnull', False)), fields=('shift', 'vehicle'), name='unique_vehicle_per_shift'),
        ),
    ]
