# Generated by Django 4.2.8 on 2026-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='planning_as_status_8ceb33_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['employee'], name='planning_as_employe_df470a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['shift'], name='planning_as_shift_i_bf9c60_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date', 'status'], name='planning_sh_date_79ce2b_idx'),
        ),
    ]
