# Generated by Django 4.2.8 on 2026-01-15 09:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Format: YYYY-MM', max_length=7, verbose_name='Période (YYYY-MM)')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('calculated', 'Calculée'), ('validated', 'Validée'), ('processed', 'Traitée'), ('paid', 'Payée')], default='draft', max_length=20, verbose_name='Statut')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Total heures')),
                ('normal_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Heures normales')),
                ('night_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Heures de nuit')),
                ('sunday_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Heures dimanche')),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Heures féries')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Heures supplémentaires')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salaire brut')),
                ('normal_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salaire normal')),
                ('night_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salaire nuit')),
                ('sunday_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salaire dimanche')),
                ('holiday_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salaire féries')),
                ('overtime_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salaire heures supplémentaires')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total déductions')),
                ('social_security', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cotisations sociales')),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Impôts')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Autres déductions')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salaire net')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Calculée le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validée le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='Employé')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payrolls', to='employees.employee', verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-period', 'employee'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la grille')),
                ('level', models.CharField(choices=[('smic', 'SMIC'), ('qualified', 'Qualifié'), ('senior', 'Senior'), ('manager', 'Manager')], max_length=20, verbose_name='Niveau')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Taux horaire de base (€)')),
                ('night_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('3.0'))], verbose_name='Multiplicateur nuit')),
                ('sunday_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('3.0'))], verbose_name='Multiplicateur dimanche')),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('3.0'))], verbose_name='Multiplicateur férié')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('3.0'))], verbose_name='Multiplicateur heures supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Grille salariale',
                'verbose_name_plural': 'Grilles salariales',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('salary', 'Salaire'), ('bonus', 'Prime'), ('deduction', 'Déduction'), ('advance', 'Avance')], max_length=20, verbose_name='Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payroll', verbose_name='Fiche de paie')),
            ],
            options={
                'verbose_name': 'Élément de paie',
                'verbose_name_plural': 'Éléments de paie',
                'ordering': ['payroll', 'item_type'],
            },
        ),
    ]
