# Generated by Django 4.2.8 on 2026-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la cotisation')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Taux (%)')),
                ('ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plafond (€)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotisation sociale',
                'verbose_name_plural': 'Cotisations sociales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la variable')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, help_text='% ou €', max_length=20, verbose_name='Unité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variable de paie',
                'verbose_name_plural': 'Variables de paie',
                'ordering': ['name'],
            },
        ),
    ]
