# Generated by Django 4.2.8 on 2026-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollcontribution_payrollvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcontribution',
            name='is_patronal',
            field=models.BooleanField(default=False, help_text="Cochez si c'est une cotisation patronale (à charge de l'employeur)", verbose_name='Cotisation patronale (employeur)'),
        ),
    ]
