# Generated by Django 4.2.8 on 2026-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollcontribution_is_patronal'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcontribution',
            name='assiette_type',
            field=models.CharField(choices=[('BRUT', 'Salaire brut (100%)'), ('ABATTUE_9825', 'Salaire abattu (98.25% du brut)'), ('PLAFONNEE', 'Salaire plafonné')], default='BRUT', help_text='Base de calcul : brut, abattu 98.25% (CSG/CRDS), ou plafonné', max_length=20, verbose_name="Type d'assiette"),
        ),
        migrations.AddField(
            model_name='payrollcontribution',
            name='deductible_fiscalement',
            field=models.BooleanField(default=False, help_text='La cotisation réduit-elle le revenu imposable ?', verbose_name='Déductible fiscalement'),
        ),
        migrations.AddField(
            model_name='payrollcontribution',
            name='organisme',
            field=models.CharField(choices=[('URSSAF', 'URSSAF'), ('AGIRC_ARRCO', 'AGIRC-ARRCO'), ('POLE_EMPLOI', 'Pôle Emploi'), ('AUTRE', 'Autre')], default='URSSAF', max_length=20, verbose_name='Organisme collecteur'),
        ),
        migrations.AddField(
            model_name='payrollcontribution',
            name='tranche_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pour les cotisations par tranche (ex: T2 commence à 3864€)', max_digits=10, null=True, verbose_name='Tranche min (€)'),
        ),
    ]
