# Generated by Django 4.2.8 on 2026-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollcontribution_assiette_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['year', 'month'], name='payroll_pay_year_4629aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payroll_pay_status_465a76_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee'], name='payroll_pay_employe_3f4ed2_idx'),
        ),
    ]
