# Generated by Django 4.2.8 on 2026-01-14 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(help_text='Identifiant interne du véhicule', max_length=50, unique=True)),
                ('registration_number', models.CharField(help_text='Immatriculation du véhicule (ex: AB-123-CD)', max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('vsl', 'VSL - Véhicule Sanitaire Léger'), ('taxi', 'Taxi')], help_text='Type de véhicule', max_length=20)),
                ('brand', models.CharField(help_text='Marque du véhicule (ex: Mercedes, Renault)', max_length=100)),
                ('model', models.CharField(help_text='Modèle du véhicule', max_length=100)),
                ('year', models.IntegerField(help_text='Année de fabrication')),
                ('color', models.CharField(blank=True, help_text='Couleur du véhicule', max_length=50)),
                ('seats_count', models.IntegerField(default=3, help_text='Nombre de places (y compris conducteur)')),
                ('stretcher_capacity', models.IntegerField(default=1, help_text='Nombre de brancards pouvant être transportés')),
                ('initial_mileage', models.IntegerField(default=0, help_text='Kilométrage initial (entrée en service)')),
                ('current_mileage', models.IntegerField(default=0, help_text='Kilométrage actuel')),
                ('fuel_type', models.CharField(blank=True, help_text='Type de carburant (essence, diesel, électrique, etc.)', max_length=50)),
                ('consumption_per_100km', models.DecimalField(blank=True, decimal_places=2, help_text='Consommation moyenne (l/100km)', max_digits=5, null=True)),
                ('purchase_date', models.DateField(help_text="Date d'achat du véhicule")),
                ('entry_date', models.DateField(help_text="Date d'entrée en service")),
                ('exit_date', models.DateField(blank=True, help_text='Date de sortie du service', null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service'), ('retired', 'Retiré du service')], default='available', help_text='Statut actuel du véhicule', max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, help_text='Date de la dernière maintenance', null=True)),
                ('next_maintenance_date', models.DateField(blank=True, help_text='Date prévue de la prochaine maintenance', null=True)),
                ('last_inspection_date', models.DateField(blank=True, help_text='Date du dernier contrôle technique', null=True)),
                ('next_inspection_date', models.DateField(blank=True, help_text='Date du prochain contrôle technique', null=True)),
                ('insurance_policy_number', models.CharField(blank=True, help_text="Numéro de police d'assurance", max_length=100)),
                ('insurance_expiry_date', models.DateField(blank=True, help_text="Date d'expiration de l'assurance", null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes et observations sur le véhicule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Utilisateur qui a créé le véhicule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['vehicle_id'],
                'indexes': [models.Index(fields=['vehicle_id'], name='vehicles_ve_vehicle_5ac43f_idx'), models.Index(fields=['registration_number'], name='vehicles_ve_registr_3774f3_idx'), models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'), models.Index(fields=['vehicle_type'], name='vehicles_ve_vehicle_76fbe4_idx')],
            },
        ),
    ]
