# Generated by Django 4.2.8 on 2026-01-15 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Année')),
                ('month', models.IntegerField(help_text='Mois (1-12)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('paid', 'Payé')], default='draft', help_text='Statut de la feuille de temps', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Date de soumission', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text="Date d'approbation", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Approuvé par', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employé', on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Feuille de temps',
                'verbose_name_plural': 'Feuilles de temps',
                'ordering': ['-year', '-month', 'employee__user__last_name'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TimeSheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date du travail')),
                ('hour_type', models.CharField(choices=[('normal', 'Heures normales'), ('night', 'Heures de nuit'), ('sunday', 'Heures dimanche'), ('holiday', 'Heures féries'), ('overtime', 'Heures supplémentaires')], help_text="Type d'heures", max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text="Nombre d'heures travaillées", max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Taux horaire', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, help_text='Assignment lié', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_entries', to='planning.assignment')),
                ('timesheet', models.ForeignKey(help_text='Feuille de temps', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.timesheet')),
            ],
            options={
                'verbose_name': 'Entrée feuille de temps',
                'verbose_name_plural': 'Entrées feuille de temps',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='Date de début')),
                ('date_end', models.DateField(help_text='Date de fin')),
                ('absence_type', models.CharField(choices=[('sick', 'Maladie'), ('vacation', 'Congés'), ('unpaid', 'Absent non justifié'), ('maternal', 'Congé maternité'), ('paternal', 'Congé paternité'), ('personal', 'Raison personnelle')], help_text="Type d'absence", max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes (certificat médical, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employé', on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_start'],
            },
        ),
    ]
