# Generated by Django 4.2.8 on 2026-01-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerecord',
            name='absence_type',
            field=models.CharField(choices=[('sick', 'Maladie'), ('vacation', 'Congés'), ('unpaid', 'Absent non justifié'), ('maternal', 'Congé maternité'), ('paternal', 'Congé paternité'), ('personal', 'Raison personnelle')], help_text="Type d'absence", max_length=20, verbose_name="Type d'absence"),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='date_end',
            field=models.DateField(help_text='Date de fin', verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='date_start',
            field=models.DateField(help_text='Date de début', verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='employee',
            field=models.ForeignKey(help_text='Employé', on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employee', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes (certificat médical, etc.)', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text="Date d'approbation", null=True, verbose_name='Approuvé le'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Approuvé par', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(help_text='Employé', on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(help_text='Mois (1-12)', verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes additionnelles', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('paid', 'Payé')], default='draft', help_text='Statut de la feuille de temps', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Date de soumission', null=True, verbose_name='Soumis le'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='year',
            field=models.IntegerField(help_text='Année', verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='Assignment lié', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_entries', to='planning.assignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='date',
            field=models.DateField(help_text='Date du travail', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='hour_type',
            field=models.CharField(choices=[('normal', 'Heures normales'), ('night', 'Heures de nuit'), ('sunday', 'Heures dimanche'), ('holiday', 'Heures féries'), ('overtime', 'Heures supplémentaires')], help_text="Type d'heures", max_length=20, verbose_name="Type d'heures"),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Taux horaire', max_digits=10, verbose_name='Taux horaire'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, help_text="Nombre d'heures travaillées", max_digits=5, verbose_name='Heures travaillées'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes additionnelles', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='timesheet',
            field=models.ForeignKey(help_text='Feuille de temps', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.timesheet', verbose_name='Feuille de temps'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
