# Generated by Django 4.2.8 on 2026-01-16 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheets', '0002_alter_absencerecord_absence_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_adjustment', models.DecimalField(decimal_places=2, help_text="Nombre d'heures à ajouter (positif) ou retirer (négatif). Exemple: +2.5 ou -1", max_digits=5, verbose_name="Ajustement d'heures")),
                ('reason', models.CharField(help_text="Raison de l'ajustement (ex: Heures supplémentaires, Erreur de saisie, etc.)", max_length=200, verbose_name='Raison')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', help_text="Statut de l'ajustement", max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text="Notes additionnelles de l'administrateur", verbose_name="Notes de l'admin")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Administrateur qui a approuvé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('timesheet', models.ForeignKey(help_text='Feuille de temps', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='timesheets.timesheet', verbose_name='Feuille de temps')),
            ],
            options={
                'verbose_name': 'Ajustement feuille de temps',
                'verbose_name_plural': 'Ajustements feuilles de temps',
                'ordering': ['-created_at'],
            },
        ),
    ]
