# Generated by Django 4.2.8 on 2026-01-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_timesheetadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetadjustment',
            name='hour_type',
            field=models.CharField(choices=[('normal', 'Heures normales'), ('night', 'Heures de nuit'), ('sunday', 'Heures dimanche'), ('holiday', 'Heures féries'), ('overtime', 'Heures supplémentaires')], default='overtime', help_text="Type d'heures ajustées", max_length=20, verbose_name="Type d'heures"),
        ),
    ]
