# Generated by Django 4.2.8 on 2026-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_timesheetadjustment_hour_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['year', 'month'], name='timesheets__year_3134ba_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['status'], name='timesheets__status_d1d005_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['employee'], name='timesheets__employe_1c605d_idx'),
        ),
    ]
